services:
  kb-scorer:
    build: . # Use the Dockerfile in the current directory
    volumes:
      - .:/app
      - ./data:/app/data
      - ./reports:/app/reports
    env_file:
      - .env
    command: python main.py